name: jais
description: A Flutter application by Ziedelth for mobile members

publish_to: 'none'
version: 2.1.2+16

environment:
  sdk: ">=2.19.0 <4.0.0"
  flutter: ">=3.7.0"

dependencies:
  cached_network_image: ^3.2.3
  firebase_core: ^2.6.1
  firebase_messaging: ^14.2.5
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  google_mobile_ads: ^2.3.0
  http: ^0.13.5
  internet_connection_checker: ^1.0.0+1
  intl: ^0.18.0
  json_annotation: ^4.8.0
  local_notifier: ^0.1.5
  provider: ^6.0.5
  shared_preferences: ^2.0.18
  shimmer: ^2.0.0
  system_tray: ^2.0.2
  url_launcher: ^6.1.10
  web_socket_channel: ^2.3.0
  window_manager: ^0.3.0

dev_dependencies:
  build_runner: ^2.3.3
  dart_code_metrics: ^5.6.0
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
  flutter_test:
    sdk: flutter
  json_serializable: ^6.6.1
  lint: ^2.0.1
  msix: ^3.7.0
  nock: ^1.2.1

flutter_icons:
  image_path: 'assets/icon.png'
  android: true
  ios: true
  windows:
    generate: true
    image_path: 'assets/icon.png'
    icon_size: 64

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: 'assets/icon.png'

flutter:
  uses-material-design: true

  assets:
    - 'assets/icon.png'
    - 'assets/icon.ico'
    - 'assets/no_connection.png'
    - 'assets/no_element.png'

  fonts:
    - family: 'Pacifico'
      fonts:
        - asset: 'assets/fonts/Pacifico-Regular.ttf'

msix_config:
  display_name: Jais
  publisher_display_name: Ziedelth
  identity_name: Ziedelth.Jais
  msix_version: 2.1.2.0
  logo_path: assets/icon.png
  capabilities: internetClient
