name: jais
description: A Flutter application by Ziedelth for mobile members

publish_to: 'none'
version: 1.1.3+10

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  cached_network_image: ^3.2.2
  firebase_core: ^2.3.0
  firebase_messaging: ^14.1.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  google_fonts: ^3.0.1
  google_mobile_ads: ^2.3.0
  http: ^0.13.5
  in_app_review: ^2.0.4
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.7.0
  mobile_scanner: ^2.0.0
  provider: ^6.0.4
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  url_launcher: ^6.1.6

dev_dependencies:
  build_runner: ^2.3.2
  flutter_launcher_icons_maker: ^0.10.2
  flutter_lints: ^2.0.1
  flutter_native_splash: ^2.2.14
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  json_serializable: ^6.5.4

flutter_icons:
  image_path: 'assets/icon.png'
  android: true
  ios: true

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: 'assets/icon.png'

flutter:
  uses-material-design: true

  assets:
    - 'assets/icon.png'
    - 'assets/no_connection.png'
    - 'assets/no_element.png'
