name: jais
description: A Flutter application by Ziedelth for mobile members

publish_to: 'none'
version: 2.0.0+12

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  flutter:
    sdk: flutter
  freezed_annotation: ^2.2.0
  google_fonts: ^4.0.0
  google_mobile_ads: ^2.3.0
  http: ^0.13.5
  internet_connection_checker: ^1.0.0+1
  json_annotation: ^4.8.0
  local_notifier: ^0.1.5
  provider: ^6.0.5
  shared_preferences: ^2.0.17
  shimmer: ^2.0.0
  system_tray: ^2.0.2
  url_launcher: ^6.1.8
  window_manager: ^0.3.0

dev_dependencies:
  build_runner: ^2.3.3
  flutter_launcher_icons: ^0.11.0
  flutter_native_splash: ^2.2.16
  json_serializable: ^6.6.0
  lint: ^2.0.1

flutter_icons:
  image_path: 'assets/icon.png'
  android: true
  ios: true
  windows:
    generate: true
    image_path: 'assets/icon.png'
    icon_size: 64

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: 'assets/icon.png'

flutter:
  uses-material-design: true

  assets:
    - 'assets/icon.png'
    - 'assets/icon.ico'
    - 'assets/no_connection.png'
    - 'assets/no_element.png'
