name: jais
description: A Flutter application by Ziedelth for mobile members

publish_to: 'none'
version: 2.5.5+2505

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  app_settings: ^5.1.1
  cached_network_image: ^3.3.0
  firebase_core: ^2.22.0
  firebase_messaging: ^14.7.3
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9
  google_mobile_ads:
    git:
      url: https://github.com/googleads/googleads-mobile-flutter.git
      path: packages/google_mobile_ads
  http: ^1.1.0
  intl: ^0.18.1
  json_annotation: ^4.8.1
  permission_handler: ^11.0.1
  provider: ^6.1.1
  shared_preferences: ^2.2.2
  shimmer: ^3.0.0
  url_launcher: ^6.2.1

dev_dependencies:
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  flutter_native_splash: ^2.3.5
  json_serializable: ^6.7.1

flutter_icons:
  image_path: 'assets/icon.png'
  adaptive_icon_background: 'assets/icon.png'
  adaptive_icon_foreground: 'assets/icon.png'
  android: true
  ios: true

flutter_native_splash:
  color: "#ffffff"
  color_dark: "#000000"
  image: 'assets/icon.png'

flutter:
  uses-material-design: true

  assets:
    - assets/icon.png
    - assets/no.png
    - assets/x-twitter.svg
    - shorebird.yaml
